### ISSUE TITLE
Parse tree too deep

### ISSUE THREAD

**Issue by pcj** [pubref/rules_protobuf#21]
Travis build failing from new closure test for the proto rule in https://github.com/pubref/rules_protobuf/commit/c8bfa53e6e4278bf4d6d24bf8b99e7454e6da32c:

```sh
external/closure_library/closure/goog/transpile.js:1460: ERROR - Parse tree too deep.
_.dg=function wY(){return this.f.a};_.eg=function xY(){return jY(this).eg()};_.fg=function yY(){return jY(this).fg()};_.gg=function zY(){return this.a.gg()};_.yd=function AY(){return this.f.a};var KE=K9b(118);gQ(614,1,{},DY);var JE=K9b(614);gQ(159,1,{},NY);_.yd=function PY(){return Cd(zd(Ad(Ad(zd(zd(zd(Ad(Ad(zd(zd(Ad(Ad(Ad(Ad(yd(Ad(Ad(Ad(Ad(Ad(Ad(Ad(Ad(zd(zd(zd(zd(zd(Ad(zd(zd(zd(Ad(zd(Ad(Ad(Ad(Ad(Ad(zd(zd(Ad(Ad(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(Ad(Ad(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(zd(Ad(zd(zd(Ad(Ad(zd(zd(zd(zd(Ad(zd(Ad(Ad(yd(zd(zd(Ad(yd(zd(zd(Ad(Ad(zd(zd(Ad(zd(Ad(Ad(Ad(Ad(Ad(Ad(Ad(zd(zd(zd(zd(zd(zd(zd(zd(zd(Ad(Ad(zd(zd(zd(zd(zd(Ad(zd(zd(zd(Ad(Ad(Ad(zd(zd(zd(Ad(Ad(Ad(zd(zd(zd(Ad(zd(Ad(Ad(zd(Ad(zd(zd(Ad(Ad(Ad(zd(zd(zd(zd(zd(Ad(zd(zd(zd(zd(zd(zd(Ad(zd(zd(zd(zd(zd(zd(Ad(Ad(Ad(Ad(Ad(zd(zd(Ad(zd(zd(Ad(Ad(zd(zd(zd(Ad(Ad(zd(Ad(zd(Bd(new Dd((E9b(WE),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ^

```

https://travis-ci.org/pubref/rules_protobuf/jobs/164838447

Should be fixed by upgrade to https://github.com/bazelbuild/rules_closure/commit/9e92334b4c07d706ade75c60da612324df396ffc but users will have to have at least this version in their workspace.
